name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
        - master
        - akg
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Retrieve openssl source
    - name: Retrieve openssl
      run: wget -O openssl.tar.gz https://www.openssl.org/source/openssl-1.1.1g.tar.gz

    - name: Extract and compile
      run: |
        tar xvzf openssl.tar.gz
        cd openssl-1.1.1g
        ./config
        make

    - name: Test
      run: make test

    - name: Package
      run: tar cvzf ../libssl.tar.gz libcrypto.so* libssl.so*


    - name: Updload library
      uses: actions/upload-artifact@v2
      with:
        name: libssl
        path: libssl.tar.gz

